remove .vscode directory from github
adobe/reactor-extension-alloy pull request #227
Opened 2022-04-28 21:09 UTC by jonsnyder

## Description

I noticed that ".vscode" was added to the repo. I added an ignore to my local .gitignore so I won't accidentally do it again.

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.
- [ ] I've updated the schema in extension.json or no changes are necessary.
- [ ] My change requires a change to the documentation.

2022-04-28 22:06 UTC, carterworks requested changes
We should add it to the project's shared `.gitignore` so that it doesn't happen again.

2022-05-19 16:31 UTC, jfkhoury approved these changes

2022-05-20 09:00 UTC, ninaceban approved these changes

2022-05-20 16:57 UTC, jonsnyder commented
> We should add it to the project's shared `.gitignore` so that it doesn't happen again.

Historically we haven't done this. Adding folders to .gitignore for every editor we use could be huge.

2022-05-20 16:57 UTC, merged