Added high entropy user-agent client hints context option
adobe/reactor-extension-alloy pull request #255
Opened 2022-09-26 07:01 UTC by liljenback

## Description

Added an optional setting for context properties to collect high entropy user-agent client hints `highEntropyUserAgentHints`.

## Related Issue

[PDCL-8422](https://jira.corp.adobe.com/browse/PDCL-8422)

## Motivation and Context

Regular user-agent is being reduced in Chromium browsers where some information is only made available through this new API.

## Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/2584844/192213129-b1939104-72d1-4e60-8403-add7d804d1c2.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.
- [x] I've updated the schema in extension.json or no changes are necessary.
- [x] My change requires a change to the documentation.

2022-09-26 15:19 UTC, carterworks approved these changes

2022-09-26 15:33 UTC, jfkhoury commented on src/view/configuration/dataCollectionSection.jsx
> +    context: contextOptions.reduce((result, option) => {
I agree, might be more readable

2022-09-26 15:44 UTC, jonsnyder requested changes
Thanks for tackling this! Sorry to throw you into the deep end with the changes necessary to the XDM object data element.

2022-09-26 15:44 UTC, jonsnyder commented on src/view/dataElements/xdmObject/constants/defaultFormState.js
> +  highEntropyUserAgentHints: CONTEXT_HIGH_ENTROPY_USER_AGENT_HINTS,
We discussed on Slack how this needs to change.

2022-09-26 15:44 UTC, jonsnyder commented on test/functional/configuration/configuration.spec.js
Add or augment test cases to make sure that:
 * checking the new checkbox leads to the correct context array in settings.
 * loading the settings with the new context automatically checks the new checkbox.

2022-09-27 14:28 UTC, ninaceban approved these changes
looks good to me!

2022-09-27 16:05 UTC, jonsnyder approved these changes

2022-09-27 16:16 UTC, merged