Added onBeforeLinkClickSend callback function
adobe/reactor-extension-alloy pull request #282
Opened 2023-02-24 14:19 UTC by ninaceban

## Description

Added the `onBeforeLinkClickSend` callback that will allow the customers to filter the link tracking and also to augment the xdm data that is send to the server.
## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.
- [ ] I've updated the schema in extension.json or no changes are necessary.
- [ ] My change requires a change to the documentation.

2023-02-24 15:39 UTC, carterworks approved these changes

2023-02-27 17:23 UTC, jonsnyder requested changes

2023-02-27 17:23 UTC, jonsnyder commented on extension.json
>              "required": ["edgeConfigId", "name"],
You need to add a "function" type transform for onBeforeLinkClickSend. Look at line 129 for how it works with onBeforeEventSend.

2023-03-21 14:38 UTC, carterworks approved these changes

2023-03-21 18:27 UTC, jonsnyder approved these changes

2023-03-21 18:27 UTC, jonsnyder commented on src/view/configuration/dataCollectionSection.jsx
> +                  description='Callback function for modifying data before each link click event is sent to the server. A variable named "content" will be available for use within your custom code. F
I would remove the quotes around false. They may try to return the string "false".

2023-03-27 16:52 UTC, merged