Fixed an issue where saving
adobe/reactor-extension-alloy pull request #369
Opened 2023-11-28 16:55 UTC by carterworks

## Description

The `<Overrides/>` React component was looking for the `datastreamId` for every config overrides environment, even if that environment had no settings. If an environment had no settings, then it would be looking for a `datastreamId` on `undefined`, which crashes the extension.

## Related Issue

[PDCL-11375: Setting Third Party Sync ID and saving break the extension](https://jira.corp.adobe.com/browse/PDCL-11375)

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.
- [x] I've updated the schema in extension.json or no changes are necessary.
- [ ] My change requires a change to the documentation.

2023-11-28 17:03 UTC, jfkhoury commented
Nice. Is this unit testable?

2023-11-29 18:38 UTC, jonsnyder requested changes
I'd like to see a functional test that reproduces this bug.

2023-12-15 22:07 UTC, carterworks commented
> I'd like to see a functional test that reproduces this bug.

@jonsnyder and @ninaceban 
I have written a functional test to repro the bug. Please re-review.

2024-01-09 00:02 UTC, jonsnyder approved these changes

2024-01-09 00:02 UTC, merged