Added a new feature to toggle between technical names and display names in the XDM Object
adobe/reactor-extension-alloy pull request #446
Opened 2024-11-22 17:11 UTC by shammowla

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.
- [ ] I've updated the schema in extension.json or no changes are necessary.
- [ ] My change requires a change to the documentation.

2024-11-22 18:09 UTC, carterworks commented
There are 7 failing tests, all around update variable. I am going to go check the other PRs, but I'm pretty sure that they are failing on the other open PRs as well, meaning that they are not related to your changes.

<ul>
  <li>
    <details>
      <summary>× Update variable action view - Allows the user to select a data element</summary>

      1) AssertionError: expected { Object (dataElementId, data, ...) } to deeply equal { Object (data, dataElementId,
      ...) }

      + expected - actual

      data: {}
      dataElementId: 'DE2'
      schema: {
      id: 'https://ns.adobe.com/unifiedjsqeonly/schemas/8f9fc4c28403e4428bbe7b97436322c44a71680349dfd489'
      - version: '1.5'
      + version: '1.4'
      }
      }

      v
      Browser: Chrome 129.0.0.0 / Windows 11

      95 | .expect(valid)
      96 | .notOk("Expected settings to not be valid when they were valid");
      97 | },
      98 | async expectSettings(expectedSettings) {
      99 | const actualSettings = await getSettings();
      > 100 | await t.expect(actualSettings).eql(expectedSettings);
      101 | },
      102 | async expectSettingsToContain(expectedSettings) {
      103 | const actualSettings = await getSettings();
      104 | await t.expect(actualSettings).contains(expectedSettings);
      105 | },

      at &lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:100:38)
      at asyncGeneratorStep
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:1:1328)
      at _next
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:1:1577)

    </details>
  </li>
  <li>
    <details>
      <summary>× Update variable action view - Allows the user to select a data element and set the XDM</summary>

      1) AssertionError: expected { Object (dataElementId, data, ...) } to deeply equal { Object (data, dataElementId,
      ...) }

      + expected - actual

      }
      dataElementId: 'DE2'
      schema: {
      id: 'https://ns.adobe.com/unifiedjsqeonly/schemas/8f9fc4c28403e4428bbe7b97436322c44a71680349dfd489'
      - version: '1.5'
      + version: '1.4'
      }
      }


      Browser: Chrome 129.0.0.0 / Windows 11

      95 | .expect(valid)
      96 | .notOk("Expected settings to not be valid when they were valid");
      97 | },
      98 | async expectSettings(expectedSettings) {
      99 | const actualSettings = await getSettings();
      > 100 | await t.expect(actualSettings).eql(expectedSettings);
      101 | },
      102 | async expectSettingsToContain(expectedSettings) {
      103 | const actualSettings = await getSettings();
      104 | await t.expect(actualSettings).contains(expectedSettings);
      105 | },

      at &lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:100:38)
      at asyncGeneratorStep
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:1:1328)
      at _next
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:1:1577)

    </details>
  </li>
  <li>
    <details>
      <summary>× Update variable action view - Allows the user to clear the root level</summary>

      1) AssertionError: expected { Object (dataElementId, data, ...) } to deeply equal { Object (data, dataElementId,
      ...) }

      + expected - actual

      data: {}
      dataElementId: 'DE2'
      schema: {
      id: 'https://ns.adobe.com/unifiedjsqeonly/schemas/8f9fc4c28403e4428bbe7b97436322c44a71680349dfd489'
      - version: '1.5'
      + version: '1.4'
      }
      transforms: {
      '': {
      clear: true


      Browser: Chrome 129.0.0.0 / Windows 11

      95 | .expect(valid)
      96 | .notOk("Expected settings to not be valid when they were valid");
      97 | },
      98 | async expectSettings(expectedSettings) {
      99 | const actualSettings = await getSettings();
      > 100 | await t.expect(actualSettings).eql(expectedSettings);
      101 | },
      102 | async expectSettingsToContain(expectedSettings) {
      103 | const actualSettings = await getSettings();
      104 | await t.expect(actualSettings).contains(expectedSettings);
      105 | },

      at &lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:100:38)
      at asyncGeneratorStep
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:1:1328)
      at _next
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/extensionViewController.mjs:1:1577)
    </details>
  </li>
  <li>
    <details>
      <summary>× Update variable action view - keeps data around when changing data elements and schema objects
      </summary>

      1) The specified selector does not match any element in the DOM tree.

      > | Selector('[data-test-id='xdmTree']')
      | .find('[data-test-id='xdmTreeNodeTitleDisplayName']')
      | .withText('otherField')
      | .parent('[data-test-id='xdmTreeNodeTitle']')
      | .nth(0)

      Browser: Chrome 129.0.0.0 / Windows 11

      50 | .parent(".ant-tree-treenode")
      51 | .nth(0)
      52 | .find(".ant-tree-switcher");
      53 | return {
      54 | click: async () => {
      > 55 | await t.click(node);
      56 | },
      57 | toggleExpansion: async () => {
      58 | await t.click(expansionToggle);
      59 | // wait for animation to finish
      60 | await t.wait(100);

      at Object.&lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:55:17)
      at asyncGeneratorStep
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:68)
      at _next
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:317)
      at &lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:448)
      at Object.&lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:247)
      at Object.click [as click]
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:56:47)
      at &lt;anonymous&gt;
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/actions/updateVariable.spec.mjs:235:40)
      at asyncGeneratorStep
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/actions/updateVariable.spec.mjs:1:68)
      at _next
      (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/actions/updateVariable.spec.mjs:1:317)

    </details>
  </li>
  <li>
    <details>
      <summary>× Update variable action view - keeps data around when changing data elements and schema arrays</summary>

      1) The specified selector does not match any element in the DOM tree.

      > | Selector('[data-test-id='xdmTree']')
      | .find('[data-test-id='xdmTreeNodeTitleDisplayName']')
      | .withText('Item 1')
      | .parent('[data-test-id='xdmTreeNodeTitle']')
      | .nth(0)
      | .parent('.ant-tree-treenode')
      | .nth(0)
      | .find('.ant-tree-switcher')

      Browser: Chrome 129.0.0.0 / Windows 11

      53 | return {
      54 | click: async () => {
      55 | await t.click(node);
      56 | },
      57 | toggleExpansion: async () => {
      > 58 | await t.click(expansionToggle);
      59 | // wait for animation to finish
      60 | await t.wait(100);
      61 | },
      62 | expectInViewport: async ( [...]

2024-12-03 17:32 UTC, jonsnyder approved these changes
The code looks good. Let's do another demo in standup.

2024-12-03 17:32 UTC, jonsnyder commented on test/functional/helpers/objectEditor/xdmTree.mjs
> +  enableDisplayNames: async () => {
Probably better to call this "toggleDisplayNames"

2024-12-03 18:04 UTC, carterworks requested changes
Resolve the two new failing tests and we are golden.

<ul>
  <li>
    <details>
      <summary>× XDM Object Display Names - toggles between display names and field IDs</summary>
      <pre>
   1) AssertionError: expected undefined to be truthy
      Browser: Chrome 129.0.0.0 / Windows 11
         30 |  await schemaField.selectMenuOption("XDM Object Data Element Tests");
         31 |  await xdmTree.node("_unifiedjsqeonly").toggleExpansion();
         32 |  await xdmTree.node("vendor").toggleExpansion();
         33 |
         34 |  // Initially should show field IDs (default)
       > 35 |  await t.expect(xdmTree.node("name").exists).ok();
         36 |
         37 |  // Toggle to show display names
         38 |  await xdmTree.enableDisplayNames();
         39 |  await t.expect(xdmTree.node("Name").exists).ok();
         40 |
         at <anonymous> (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/dataElements/xdmObjectDisplayNames.spec.mjs:35:47)
         at asyncGeneratorStep (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/dataElements/xdmObjectDisplayNames.spec.mjs:1:68)
         at _next (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/dataElements/xdmObjectDisplayNames.spec.mjs:1:317)
</pre>
    </details>
  </li>
  <li>
    <details>
      <summary>× XDM Object Editing - allows user to provide individual array items</summary>
      <pre>
   1) The specified selector does not match any element in the DOM tree.
       > | Selector('[data-test-id='xdmTree']')
         |   .find('[data-test-id='xdmTreeNodeTitleDisplayName']')
         |   .withText(/^implementationDetails$|^implementationdetails$/i)
         |   .parent('[data-test-id='xdmTreeNodeTitle']')
         |   .nth(0)
         |   .parent('.ant-tree-treenode')
         |   .nth(0)
         |   .find('.ant-tree-switcher')
      Browser: Chrome 129.0.0.0 / Windows 11
         54 |  return {
         55 |    click: async () => {
         56 |      await t.click(node);
         57 |    },
         58 |    toggleExpansion: async () => {
       > 59 |      await t.click(expansionToggle);
         60 |      // wait for animation to finish
         61 |      await t.wait(100);
         62 |    },
         63 |    expectInViewport: async () => {
         64 |      const isElementInViewport = await getIsElementInViewport(node);
         at Object.<anonymous> (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:59:17)
         at asyncGeneratorStep (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:68)
         at _next (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:317)
         at <anonymous> (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:448)
         at Object.<anonymous> (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:1:247)
         at Object.toggleExpansion [as toggleExpansion] (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/helpers/objectEditor/xdmTree.mjs:62:58)
         at <anonymous> (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/dataElements/xdmObjectEditing.spec.mjs:37:49)
         at asyncGeneratorStep (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/dataElements/xdmObjectEditing.spec.mjs:1:68)
         at _next (file:///D:/sauce-testcafe-runner/3.10.0/bundle/__project__/test/functional/specs/view/dataElements/xdmObjectEditing.spec.mjs:1:317)
</pre>
    </details>
  </li>
</ul>

2024-12-04 19:10 UTC, carterworks approved these changes

2025-01-10 17:08 UTC, merged