Migrate from Jasmine to Vitest for unit test
adobe/reactor-extension-alloy pull request #448
Opened 2024-12-03 21:31 UTC by shammowla

## Description

## Related Issue

## Motivation and Context

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.
- [ ] I've updated the schema in extension.json or no changes are necessary.
- [ ] My change requires a change to the documentation.

2024-12-05 07:57 UTC, dompuiu commented
On my machine I get a `zsh: segmentation fault  npm run test:unit` error when I run the tests. Does that happen to you too?

2024-12-05 16:09 UTC, carterworks commented
> On my machine I get a `zsh: segmentation fault npm run test:unit` error when I run the tests. Does that happen to you too?

`npm run test:unit` works on my machine

2024-12-05 19:01 UTC, carterworks requested changes

2024-12-05 22:59 UTC, shammowla commented on test/setup.js
> +    addEventListener: vi.fn(),
Removed the global event listeners.

2024-12-05 23:00 UTC, shammowla commented
@dompuiu can you try running it now with the config updates.

2024-12-05 23:04 UTC, shammowla commented
Unit tests are running successfully on GH Actions.

2024-12-06 18:38 UTC, shammowla commented
@carterworks fixed the eslint issues. Let me know if this works

2024-12-06 18:41 UTC, carterworks commented
> @carterworks fixed the eslint issues. Let me know if this works

New issues.

```
> reactor-extension-alloy@2.27.0 lint
> eslint "*.{js,jsx}" "{src,test,scripts}/**/*.{js,jsx}" --cache --fix


./test/unit/lib/actions/updateVariable/createUpdateVariable.spec.js
   16:1  error  'describe' is not defined    no-undef
   20:3  error  'beforeEach' is not defined  no-undef
   25:3  error  'it' is not defined          no-undef
   27:5  error  'expect' is not defined      no-undef
   30:3  error  'it' is not defined          no-undef
   37:5  error  'expect' is not defined      no-undef
   40:3  error  'it' is not defined          no-undef
   47:5  error  'expect' is not defined      no-undef
   50:3  error  'it' is not defined          no-undef
   57:5  error  'expect' is not defined      no-undef
   60:3  error  'it' is not defined          no-undef
   67:5  error  'expect' is not defined      no-undef
   69:3  error  'it' is not defined          no-undef
   80:5  error  'expect' is not defined      no-undef
   83:3  error  'it' is not defined          no-undef
   90:5  error  'expect' is not defined      no-undef
   93:3  error  'it' is not defined          no-undef
  100:5  error  'expect' is not defined      no-undef

./test/unit/lib/dataElements/xdmObject/index.spec.js
  15:1  error  'describe' is not defined  no-undef
  16:3  error  'it' is not defined        no-undef
  22:5  error  'expect' is not defined    no-undef

./test/unit/lib/instanceManager/injectWrapOnBeforeEventSend.spec.js
  14:1  error  'describe' is not defined    no-undef
  18:3  error  'beforeEach' is not defined  no-undef
  34:3  error  'it' is not defined          no-undef
  36:5  error  'expect' is not defined      no-undef
  37:5  error  'expect' is not defined      no-undef
  44:5  error  'expect' is not defined      no-undef
  49:3  error  'it' is not defined          no-undef
  57:5  error  'expect' is not defined      no-undef
  58:5  error  'expect' is not defined      no-undef
  65:5  error  'expect' is not defined      no-undef
  71:3  error  'it' is not defined          no-undef
  80:5  error  'expect' is not defined      no-undef
  81:5  error  'expect' is not defined      no-undef
  88:5  error  'expect' is not defined      no-undef

./test/unit/lib/utils/clone.spec.js
  15:1  error  'describe' is not defined  no-undef
  16:3  error  'it' is not defined        no-undef
  25:5  error  'expect' is not defined    no-undef

./test/unit/lib/utils/createGetConfigOverrides.spec.js
   14:1  error  'describe' is not defined  no-undef
   17:5  error  'describe' is not defined  no-undef
   18:7  error  'it' is not defined        no-undef
   20:9  error  'expect' is not defined    no-undef
   23:7  error  'it' is not defined        no-undef
   40:9  error  'expect' is not defined    no-undef
   47:7  error  'it' is not defined        no-undef
   73:9  error  'expect' is not defined    no-undef
   93:7  error  'it' is not defined        no-undef
  106:9  error  'expect' is not defined    no-undef
  124:9  error  'expect' is not defined    no-undef
  131:7  error  'it' is not defined        no-undef
  132:9  error  'expect' is not defined    no-undef
  150:7  error  'it' is not defined        no-undef
  161:9  error  'expect' is not defined    no-undef
  176:9  error  'expect' is not defined    no-undef
  181:3  error  'it' is not defined        no-undef
  203:5  error  'expect' is not defined    no-undef

./test/unit/lib/utils/numberAwareCompareFunction.spec.js
  14:1  error  'describe' is not defined  no-undef
  15:3  error  'it' is not defined        no-undef
  16:5  error  'expect' is not defined    no-undef
  22:3  error  'it' is not defined        no-undef
  23:5  error  'expect' is not defined    no-undef
  26:3  error  'it' is not defined        no-undef
  27:5  error  'expect' is not defined    no-undef
  28:5  error  'expect' is not defined    no-undef
  29:5  error  'expect' is not defined    no-undef
  30:5  error  'expect' is not defined    no-undef
  31:5  error  'expect' is not defined    no-undef
  32:5  error  'expect' is not defined    no-undef
  35:3  error  'it' is not defined        no-undef
  36:5  error  'expect' is not defined    no-undef
  41:3  error  'it' is not defined        no-undef
  42:5  error  'expect' is not defined    no-undef
  49:3  error  'it' is not defined        no-undef
  50:5  error  'expect' is not defined    no-undef
  57:3  error  'it' is not defined        no-undef

./test/unit/lib/utils/pathUtils.spec.js
  14:1  error  'describe' is not defined  no-undef
  15:3  error  'describe' is not defined  no-undef
  16:5  error  'it' is not defined        no-undef
  17:7  error  'expect' is not defined    no-undef
  20:5  error  'it' is not defined        no-undef
  21:7  error  'expect' is not defined    no-undef
  24:5  error  'it' is not defined        no-undef
  25:7  error  'expect' is not defined    no-undef
  28:5  error  'it' is not defined        no-undef
  31:7  error  'expect' is not defined    no-undef
  34:5  error  'it' is not defined        no-undef
  35:7  error  'expect' is not defined    no-undef
  38:5  error  'it' is not defined        no-undef
  39:7  error  'expect' is not defined    no-undef
  42:5  error  'it' is not defined        no-undef
  43:7  error  'expect' is not defined    no-undef
  48:5  error  'it' is not defined        no-undef
  49:7  error  'expect' is not defined    no-undef
  53:3  error  'describe' is not defined  no-undef
  54:5  error  'it' is not defined        no-undef
  55:7  error  'expect' is not defined    no-undef
  57:5  error  'it' is not defined        no-undef
  60:7  error  'expect' is not defined    no-undef
  62:5  error  'it' is not defined        no-undef
  63:7  error  'expect' is not defined    no-undef
  65:5  error  'it' is not defined        no-undef
  68:7  error  'expect' is not defined    no-undef
  70:5  error  'it' is not defined        no-undef
  71:7  error  'expect' is not defined    no-undef

./test/unit/view/components/overrides/overridesBridge.spec.js
    25:1  error  'describe' is not defined  no-undef
    26:3  error  'describe' is not defined  no-undef
    27:5  error  'it' is not defined        no-undef
    74:7  error  'expect' is not defined    no-undef
    80:3  error  'describe' is not defined  no-undef
    81:5  error  'it' is not defined        no-undef
   258:7  error  'expect' is not defined    no-undef
   263:5  error  'it' is not defined        no-undef
   354:7  error  'expect' is not defined    no-undef
   359:5  error  'it' is not defined        no-undef
   372:7  error  'expect' is not defined    no-undef
   507:5  error  'it' is not defined        no-undef
   544:7  error  'expect' is not defined    no-undef
   638:7  error  'expect' is not defined    no-undef
   697:5  error  'it' is not defined        no-undef
   734:7  error  'expect' is not defined    no-undef
   793:5  error  'it' is not defined        no-undef
   803:7  error  'expect' is not defined    no-undef
   863:3  error  'describe' is not defined  no-undef
   864:5  error  'it' is not defined        no-undef
   917:7  error  'expect' is not defined    no-undef
   957:5  error  'it' is not defined        no-undef
   997:7  error  'expect' is not defined    no-undef
  1033:5  error  'it' is not defined        no-undef
  1054:7  error  'expect' is not defined    no-undef
  1066:5  error  'it' is not defined        no-undef
  1115:7  error  'expect' is not defined    no-undef
  1161:5  error  'it' is not defined        no-undef
  1162:7  error  'expect' is not defined    no-undef
  1169:7  error  'expect' is not defined    no-undef
  1172:5  error  'it' is not defined        no-undef
  1247:7  error  'expect' is not defined    no-undef
  1277:3  error  'describe' is not defined  no-undef
  1278:5  error  'it' is not defined        no-undef
  1280:7  error  'expect' is not defined    no-undef
  1283:5  error  'it' is not defined        no-undef
  1284:7  error  'expect' is not defined    no- [...]

2024-12-06 21:12 UTC, carterworks approved these changes

2025-01-09 20:18 UTC, merged